title: Pranjal Chakraborty
affiliation: Developer and Systems Analyst, Brock University, ON, Canada
email: pranjalchakraborty@gmail.com
description: Blog
footer_message: This blog is to share knowledge and to document my hobby projects.
baseurl: "/blog"
url: "https://www.pranjal.net"
linkedin_username: pcborty
github_username:  pranjalcborty
show_excerpts: false

paginate: 10
paginate_path: "/page-:num/"

# Build settings
theme: minima
# remote_theme: jekyll/minima
# minima:
#  skin: dark

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
