title: Pranjal Chakraborty
affiliation: Developer and Systems Analyst, Brock University, ON, Canada
email: pranjalchakraborty@gmail.com
description: Blog
footer_message: This blog is to share knowledge and to document my hobby projects.
baseurl: "/blog"
url: "https://www.pranjal.net"
linkedin_username: pcborty
github_username:  pranjalcborty
show_excerpts: false

paginate: 4
paginate_path: "/blog/page:num/"

# Build settings
# theme: minima
remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-remote-theme
